# -*- coding: utf-8 -*-
"""Rag integration with llmops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgK7wUYYjXqpMWLRczlJkJWXsRrzU_YI
"""

#!nvidia-smi

#!pip install langchain
#!pip install langchain_community
#!pip install langchain_text_splitter
#!pip install langchain_chroma
#!pip install langchain_groq
#!pip install Unstructed
#!pip install sentence-transformers

import os
from langchain_chroma import Chroma
from langchain_groq import ChatGroq
from langchain_classic.chains import RetrievalQA
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.document_loaders import UnstructuredFileIOLoader



#!pip install langsmith

import os
from langsmith import Client
#GROQ

import requests
url = "https://dspmuranchi.ac.in/pdf/Blog/python%20Built-in%20Functions.pdf"
response = requests.get(url)
with open("python_build_in_functions.pdf", "wb") as f:
  f.write(response.content)

loader = UnstructuredFileIOLoader("python_built_in_functions.pdf")

#!pip install unstructured

#!pip install "unstructured[pdf]"

text_splitter = CharacterTextSplitter(chunk_size=2000, chunk_overlap=400)

with open("python_build_in_functions.pdf", "rb") as f:
  corrected_loader = UnstructuredFileIOLoader(f)
  documents = corrected_loader.load()
# Manually add the source filename to each document's metadata
for doc in documents:
    doc.metadata['source'] = "python_build_in_functions.pdf"
texts = text_splitter.split_documents(documents)

type(texts)

texts[3]

embeddings =HuggingFaceEmbeddings()

persist_directory = 'vector_db'

vectordb = Chroma.from_documents(documents=texts, embedding=embeddings, persist_directory=persist_directory)
retriever = vectordb.as_retriever()

llm = ChatGroq(model = 'llama-3.3-70b-versatile', temperature=7)

vectordb = Chroma.from_documents(documents=texts, embedding=embeddings, persist_directory=persist_directory)

llm = ChatGroq(model = 'llama-3.3-70b-versatile', temperature=2)

qa_chain = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever, return_source_documents=True)

query = 'what are the function from the pdf'
response = qa_chain.invoke({'query': query})

print(response['result'])

query = 'what are the function from the pdf'
response = qa_chain.invoke({'query': query})
print(response['result'])
#print('*' * 30)
print('Source Document:', response['source_documents'][0].metadata['source'])

query = 'what are the lambda function & explain filter map from the pdf'
response = qa_chain.invoke({'query': query})
print(response['result'])

import gradio as gr

# Chat Function
def chatbot_response(question):
    try:
        response = qa_chain.invoke({'query': question})
        answer = response["result"]
        sources = []
        for doc in response["source_documents"]:
            if "source" in doc.metadata:
                sources.append(doc.metadata["source"])
        source_text = "\n".join(list(set(sources)))
        final_response = f"""
{answer}

Source:
{source_text}
"""
        return final_response
    except Exception as e:
        return f"Error: {str(e)}"

# Gradio UI
demo = gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(
        lines=2,
        placeholder="Ask questions from your pdf..."
    ),
    outputs="text",
    title="RAG PDF Chatbot",
    description="LLMOps project using LangChain + Groq + ChromaDB + Gradio",
    theme="soft"
)

demo.launch(debug=True)







